### ISSUE TITLE
[Q] Connections and adresses

### ISSUE THREAD

**Issue by Wafje** [stmax82/1-WireBeckhoffPLC#1]
Dear,

~~Is the 1-wire sensor connected to both the Rx and the Tx connection, essentially bridging the two connections?~~ _I should learn how to read._

How did you initially get the sensors addresses?

**Comment by stmax82** [comment]
There are some tools that can be used for that - I used Maxim's "OneWireViewer":
https://www.maximintegrated.com/en/products/ibutton/software/1wire/OneWireViewer.cfm

Make sure to enter the address in the correct order - the byte specifying the type of sensor first.
